### PR TITLE
Request to Update to Minecraft 1.8.9

### PR DESCRIPTION
**Pull request by AGEBattleSword**
I will be passing along the mod to my developers and they will simply change code to make the mod compatible with the Minecraft update for use on Minecraft servers

### CODE REVIEW

**Comment by jadar** [comment]
I'm really glad you guys are planning to contribute. We haven't had any time to work on it in the past year. My question is what exactly is the thought in merging this into master? I prefer to leave master as the place where the most stable code is. Would you prefer a new 1.8.9 branch instead?

**Comment by AGEBattleSword** [comment]
I apologize for the location of the request. I am new to GitHub, but yes,
we would like to see a 1.8.9 branch as it will be used in a major project
from Legion Gaming Community and Armory Gaming Experience to create a story
based pair of servers following two new fan made Lyoko Series.

**Comment by AGEBattleSword** [comment]
I have not tested the 1.7.10 mod but we may request some quick development
spawn eggs in the future in order to allow us to create new sectors.

**Comment by AGEBattleSword** [comment]
Our server host would also like permission to host our fork exclusively on a third party site that isnt github. This way, when special changes that are exclusive to the server.

**Comment by jadar** [comment]
I've made a branch called `1.8.9` that I believe has the latest code. Dimension support was being worked on last but never finished. You can fork to wherever you want and push changes upstream (with PRs) as you see fit.

**Comment by jadar** [comment]
I'm interested in seeing where you go with this. Definitely keep me updated.

**Comment by AGEBattleSword** [comment]
https://legiongc.com/index.php/code-lyoko-minecraft-server/ As time goes
on, this will be where you can go to see both of the server's progress

**Comment by AGEBattleSword** [comment]
Tried to launch the 1.8.9 mod into Forge Version 1.8.9 as the zip folder.
Mod is not starting. I will run my tests of the mod in 1.7.10 until I get
update information from you.

**Comment by jadar** [comment]
FYI that link isn't working yet. I assume it will be when you guys get up and running, though.

Yeah I can't imagine the update will be easy. As I remember a lot changed between 1.7 and 1.8, and lots of people were not happy. It can certainly be done if you guys are willing to put in the effort. :)

**Comment by AGEBattleSword** [comment]
We are willing to put in the effort. We want to make this server work, the
issue is I personally have no mod making experience, but if I speak to my
team I am sure we can get you as much help as possible. I will do a review
for 1.7.10 to show what works to my team and so you can see what we want to
implement into the mod.

**Pull request closed without merging**
